### ISSUE TITLE
Weird left margin

### ISSUE THREAD

**Issue by goug0035** [goug0035/dsn1675-assignment-1#1]
Hey Thomas @thomasjbradley

There is a random extra border on the left side of my header and footer.

Also the h2 "Become a member" and "now playing" float up in between the buttons when the screen gets larger.

**Comment by thomasjbradley** [comment]
I'm not completely sure what you mean. Can you take a screenshot of it for me?

**Comment by goug0035** [comment]
![screen shot 2015-09-23 at 7 27 37 pm](https://cloud.githubusercontent.com/assets/6340296/10061700/3226ffee-6229-11e5-9f4e-4e5026d4ae8b.png)

![screen shot 2015-09-23 at 7 23 47 pm](https://cloud.githubusercontent.com/assets/6340296/10061664/dfb3bef0-6228-11e5-817d-4a4819da29b8.png)

**Comment by thomasjbradley** [comment]
I don't think it's the header, but instead some of the other content.

`.wonders-info` has a margin on the left and right and a width of 100% which would cause it to be wider than the viewport.

Same thing for `.learn-more`.

**Comment by goug0035** [comment]
Thank you that fixed the extra space on the left but I still can not get the h2 to stop flowing in between the buttons

**Comment by thomasjbradley** [comment]
Maybe try adding `clear: both` to the `<h2>`; it looks like a float/clear issue to me.

**Comment by goug0035** [comment]
That fixed it thank you!
